services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Frontend\:
    resource: '../Classes/*'
    # glob for services that have been previously available as
    # container entries and have been removed in the mean time
    # (e.g. because factories are to be used instead)
    exclude: '../Classes/{Frontend/Controller/TypoScriptFrontendController.php}'

  TYPO3\CMS\Frontend\ContentObject\ContentDataProcessor:
    public: true

  TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer:
    public: true
    shared: false
    arguments:
      $typoScriptFrontendController: null

  TYPO3\CMS\Frontend\ContentObject\Exception\ProductionExceptionHandler:
    public: true
    shared: false

  TYPO3\CMS\Frontend\Resource\PublicUrlPrefixer:
    public: true

  TYPO3\CMS\Frontend\Aspect\FileMetadataOverlayAspect:
    tags:
      - name: event.listener
        identifier: 'typo3-frontend/overlay'
        method: 'languageAndWorkspaceOverlay'

  TYPO3\CMS\Frontend\Html\HtmlWorker:
    public: true

  TYPO3\CMS\Frontend\Typolink\LinkResultFactory:
    public: true
